site_name: Nix Lab
site_url: https://nixlab.srizan.dev
theme:
  name: material
  palette:
    - scheme: mocha
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to Latte
    - scheme: latte
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-partly-cloudy
        name: Switch to Mocha

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css